[package]
name = "rars"
version = "0.2.0"
description = "High-level Rust API for reading, extracting, writing, and repairing RAR archives."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
fast = ["rars-format/fast"]
parallel = ["rars-format/parallel"]

[dependencies]
rars-format.workspace = true
